In [2]:
import numpy as np

list_ = [ '1','2','3','4','5']

array_list = np.array(object = list_)

In [3]:
# Is there any difference in the data type of variables list_ and array_list? If there is then write a code 
# to print the data types of both the variables.
type(list_)

list

In [4]:
type(array_list)

numpy.ndarray

In [21]:
#  Write a code to print the data type of each and every element of both the variables list_ and arra_list
print("Data types of elements of list_ :-")
for i in (list_ ):
    print(type(i))
print("Data types os elemnts in array_list:-")
for i in (array_list):
    print(type(i))


Data types of elements of list_ :-
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Data types os elemnts in array_list:-
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


In [22]:
array_list = np.array(object = list_, dtype = int)

In [23]:
array_list

array([1, 2, 3, 4, 5])

In [24]:
# Will there be any difference in the data type of the elements present in both the variables, list_ and 
# arra_list? If so then print the data types of each and every element present in both the variables, list_ 
# and arra_list
print("Data types of elements of list_ :-")
for i in (list_ ):
    print(type(i))
print("Data types os elemnts in array_list:-")
for i in (array_list):
    print(type(i))


Data types of elements of list_ :-
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Data types os elemnts in array_list:-
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


In [25]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)
#find shape and size of num_array

In [26]:
np.shape(num_array)

(2, 3)

In [28]:
np.size(num_array)

6

In [30]:
#Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [31]:
#Create an identity matrix of shape (5,5) using numpy functions
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])